### PR TITLE
Upgrade the CI scripts to 1.1.1

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by leouieda** [comment]
I have no idea why the CI is failing. I'll try to rerun and see if this was a fluke with the conda-forge packages.

**Comment by seisman** [comment]
See the output of `conda --list`. `gdal` comes from defaults, while poppler comes from conda-forge.

**Comment by leouieda** [comment]
That shouldn't be a problem anymore. But you're right. That is because conda-forge doesn't build 3.5 packages anymore. The 3.6 error is due to not finding a remote file used in the examples. We should drop 3.5 since defaults also doesn't support it anymore.

**Comment by seisman** [comment]
OK. I'll open a new PR to add Python 3.7 and drop 3.5 later.

BTW, I don't why I lost the written permission to this repo. Now I have to clone it to my account and submit a PR there.

**Comment by leouieda** [comment]
> I don't why I lost the written permission to this repo

That's weird. I might have messed things up when I was reviewing the organization permissions. I created a team and added you to it. Should be working now.

**Comment by leouieda** [comment]
@seisman I also changed your role to "Owner" so you should have complete access to all of the organization.

**Comment by seisman** [comment]
> @seisman I also changed your role to "Owner" so you should have complete access to all of the organization.

Thanks. 😄

**Comment by seisman** [comment]
The build reports the following error:
```
error while loading shared libraries: liblapack.so.3: cannot open shared object file: No such file or directory.
```
Seems related to https://github.com/conda-forge/gmt-feedstock/pull/61.

**Comment by leouieda** [comment]
@seisman can you reproduce the error locally? Doesn't seem to happen to me.

**Comment by seisman** [comment]
@leouieda The build now works, except the remote file issue.

**Comment by leouieda** [comment]
@seisman feel free to merge if this is done. We can work on the failing test later.

**Pull request merged**
